backend:
  name: git-gateway

media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Poster Image", name: "poster_image", widget: "image" }
      - { label: "SEO Title", name: "seo_title", widget: "string" }
      - { label: "SEO Description", name: "seo_desc", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
