backend:
  name: github
  repo: TorbjornHoltmon/holtmon.dev # Your username and repository
  branch: staging # Branch to use
  base_url: https://us-central1-your-project-id.cloudfunctions.net # The base URL for your Firebase Function
  auth_endpoint: /oauth/auth # The path to the OAuth endpoint of the function

media_folder: static/images
public_folder: /images

collections:
  - name: "articles"
    label: "Article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SEO Title", name: "seo_title", widget: "string" }
      - { label: "SEO Description", name: "seo_desc", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
