# This is a basic workflow to help you get started with Actions

name: Functions deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [staging]
    paths: 
    - "functions/*"
  pull_request:
    branches: [staging]
    paths: 
    - "functions/*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: |
          npm install
          cd functions; npm install
      - name: Deploy to firebase
        run: npm run firebase:deploy -- --token '${{ secrets.FIREBASE_TOKEN }}' --only functions
